version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.3

    steps:
      - checkout

      # Docker Composeのインストール
      - run:
          name: Install Docker Compose
          command: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

      # Docker Composeの起動
      - run:
          name: Start Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d

      # Laravelの依存関係のインストール
      - run: docker-compose exec -T app composer install

      # .envファイルの設定
      - run: docker-compose exec -T app cp .env.example .env.testing

      # アプリケーションキーの生成
      - run: docker-compose exec -T app php artisan key:generate --env=testing

      # マイグレーションの実行
      - run: docker-compose exec -T app php artisan migrate --env=testing

      # PHPUnitテストの実行
      - run: docker-compose exec -T app vendor/bin/phpunit --configuration phpunit.xml --stop-on-failure

      # Docker Composeの停止
      - run:
          name: Stop Docker Compose
          command: docker-compose down

workflows:
  version: 2
  test:
    jobs:
      - build
