version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:2023.07.1
    working_directory: ~/laravel-ci

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start Docker Compose
          command: docker compose -f docker-compose.yml up -d --build

      # # Nginx コンフィグ用ディレクトリを作成
      # - run:
      #     name: Create Nginx conf directory
      #     command: docker compose exec -T nginx mkdir -p /etc/nginx/conf.d

      # # ファイルを手動でコピー
      # - run:
      #     name: Copy Nginx configuration
      #     command: cp ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf


      - run:
          name: Set permissions for default.conf
          command: |
            docker compose exec -T nginx chmod 644 /etc/nginx/conf.d/default.conf

      - run:
          name: Laravel dependency installation
          command: docker compose exec -T app composer install

      - run:
          name: Set .env file
          command: docker compose exec -T app cp .env.example .env.testing

      - run:
          name: Generate application key
          command: docker compose exec -T app php artisan key:generate --env=testing

      - run:
          name: Run migrations
          command: docker compose exec -T app php artisan migrate --env=testing

      - run:
          name: Run PHPUnit tests
          command: docker compose -f docker-compose.yml exec -T app vendor/bin/phpunit --configuration phpunit.xml --stop-on-failure

      - run:
          name: Stop Docker Compose
          command: docker compose -f docker-compose.ci.yml down

workflows:
  version: 2
  test:
    jobs:
      - build
