version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/php:8.3
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      # Docker Composeのインストール
      - run:
          name: Install Docker Compose v2.29.1
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      # Docker Composeの起動
      - run:
          name: Start Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d --build

      # コンテナの状態を確認
      - run:
          name: Check running containers
          command: docker-compose ps

      # Laravelの依存関係のインストール
      - run:
          name: Install Laravel dependencies
          command: docker-compose exec -T php composer install

      # .envファイルの設定
      - run:
          name: Set up .env
          command: docker-compose exec -T php cp .env.example .env.testing

      # アプリケーションキーの生成
      - run:
          name: Generate application key
          command: docker-compose exec -T php php artisan key:generate --env=testing

      # マイグレーションの実行
      - run:
          name: Run migrations
          command: docker-compose exec -T php php artisan migrate --env=testing

      # PHPUnitテストの実行
      - run:
          name: Run PHPUnit tests
          command: docker-compose exec -T php vendor/bin/phpunit --configuration phpunit.xml --stop-on-failure

      # Docker Composeの停止
      - run:
          name: Stop Docker Compose
          command: docker-compose down

workflows:
  version: 2
  test:
    jobs:
      - build
