version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/classic:edge
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Set environment variables
          command: echo "APP_ENV=testing" >> .env

      # Docker Composeの起動
      - run:
          name: Start Docker Compose
          command: |
            set -x
            docker compose up -d --build

      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop

      - run:
          name: Start Docker Compose
          command: |
            set -x
            docker compose up -d --build
            

      - run:
          name: Remove existing default.conf
          command: docker compose exec nginx rm /etc/nginx/conf.d/default.conf

      # Laravelの依存関係のインストール
      - run: docker compose exec -T app composer install

      # .envファイルの設定
      - run: docker compose exec -T app cp .env.example .env.testing

      # アプリケーションキーの生成
      - run: docker compose exec -T app php artisan key:generate --env=testing

      # マイグレーションの実行
      - run: docker compose exec -T app php artisan migrate --env=testing

      # PHPUnitテストの実行
      - run:
          name: Run PHPUnit tests
          command: docker compose exec -T app vendor/bin/phpunit --configuration phpunit.xml --stop-on-failure

      - run:
          name: Stop Docker Compose
          command: docker compose down

workflows:
  version: 2
  test:
    jobs:
      - build

