version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/php:8.3
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Set environment variables
          command: echo "APP_ENV=testing" >> .env

      - run:
          name: Check working directory
          command: |
            pwd
            ls -l ./docker/nginx/default.conf

      - run:
          name: Ensure correct permissions for nginx default.conf
          command: chmod 644 ./docker/nginx/default.conf

      

      # Docker Composeのインストール
      - run:
          name: Install Docker Compose v2.29.1
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      # default.conf の権限を修正
      - run:
          name: Fix permissions for default.conf
          command: chmod 644 /home/circleci/project/docker/nginx/default.conf

      - run:
          name: Verify default.conf exists
          command: ls -l ./docker/nginx/default.conf


      - run:
          name: Verify default.conf exists in CircleCI
          command: ls -la /home/circleci/project/docker/nginx/default.conf


      - run:
          name: Verify default.conf exists
          command: ls -l ./docker/nginx/default.conf
      
      - run:
          name: Verify if default.conf exists before mounting
          command: ls -l /home/circleci/project/docker/nginx/default.conf


      - run:
          name: Verify default.conf exists in CircleCI
          command: ls -la /home/circleci/project/docker/nginx/default.conf

      - run:
          name: View Nginx Logs
          command: docker compose logs nginx

      # Docker Composeの起動
      - run:
          name: Start Docker Compose
          command: |
            docker compose -f docker-compose.ci.yml up -d --build

      # コンテナの状態を確認
      - run:
          name: Check running containers
          command: docker ps

      # Laravelの依存関係のインストール
      - run: docker compose exec -T app composer install

      # .envファイルの設定
      - run: docker compose exec -T app cp .env.example .env.testing

      # アプリケーションキーの生成
      - run: docker compose exec -T app php artisan key:generate --env=testing

      # マイグレーションの実行
      - run: docker compose exec -T app php artisan migrate --env=testing

      # PHPUnitテストの実行
      - run:
          name: Run PHPUnit tests
          command: docker compose -f docker-compose.ci.yml exec -T app vendor/bin/phpunit --configuration phpunit.xml --stop-on-failure

      - run:
          name: Stop Docker Compose
          command: docker compose -f docker-compose.ci.yml down

workflows:
  version: 2
  test:
    jobs:
      - build
